// Generated by CoffeeScript 1.4.0
(function() {

  jQuery.fn.extend({
    TickTock: function(options) {
      var get_time, me;
      me = this;
      get_time = function() {
        var date, hrs, mins, secs;
        date = new Date;
        hrs = date.getHours();
        mins = date.getMinutes();
        secs = date.getSeconds();
        hrs = hrs < 10 ? "0" + hrs : hrs;
        mins = mins < 10 ? "0" + mins : mins;
        secs = secs < 10 ? "0" + secs : secs;
        return "" + hrs + ":" + mins + ":" + secs;
      };
      $(me).html(get_time());
      return setInterval((function() {
        return $(me).html(get_time());
      }), 1000);
    }
  });

}).call(this);
