// Generated by CoffeeScript 1.4.0
(function() {
  var format_number, get_time;

  format_number = function(number) {
    if (number < 10) {
      return "0" + number;
    } else {
      return number;
    }
  };

  get_time = function() {
    var time, x, _i, _len, _ref;
    x = {};
    _ref = ['Hours', 'Minutes', 'Seconds'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      time = _ref[_i];
      x[time] = format_number(new Date()["get" + time]());
    }
    return "" + x.Hours + ":" + x.Minutes + ":" + x.Seconds;
  };

  Element.prototype.TickTock = function() {
    var me;
    me = this;
    me.innerHTML = get_time();
    return setInterval((function() {
      return me.innerHTML = get_time();
    }), 1000);
  };

}).call(this);
