// Generated by CoffeeScript 1.4.0
(function() {
  var get_time;

  get_time = function() {
    var date, hrs, mins, secs;
    date = new Date;
    hrs = date.getHours();
    mins = date.getMinutes();
    secs = date.getSeconds();
    hrs = hrs < 10 ? "0" + hrs : hrs;
    mins = mins < 10 ? "0" + mins : mins;
    secs = secs < 10 ? "0" + secs : secs;
    return "" + hrs + ":" + mins + ":" + secs;
  };

  Element.prototype.TickTock = function() {
    var me;
    me = this;
    me.innerHTML = get_time();
    return setInterval((function() {
      return me.innerHTML = get_time();
    }), 1000);
  };

}).call(this);
